-- GA government bid-opportunity radar (Phase 1: Georgia only, sourced from
-- the Georgia Procurement Registry's own public search API). Scraped
-- periodically by a scheduled job hitting GPR directly — no login, no API
-- key, nothing to provision. government_opportunities is the raw feed the
-- scraper owns (upserted on (source, external_id, category), status/dates
-- refreshed from GPR on every run); government_pursuits is the separate
-- CRM-style layer where the owner actually tracks what's being chased,
-- mirroring the recommendations/activity_events split already used
-- elsewhere in the app. Additive; nothing existing changes.

create table government_opportunities (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'ga_gpr',
  -- GPR's own event identifier (e.g. PE-72155-NONST-2027-000000198).
  external_id text not null,
  category text not null check (category in ('interior_design_architecture', 'furniture_acquisition')),
  title text not null,
  agency_name text not null,
  government_type text,
  -- As reported by GPR at last fetch (Open/Closed/Awarded/etc.) — trusted
  -- verbatim rather than inferred, since the scraper re-checks it directly.
  status text not null,
  posting_date date,
  closing_date date,
  detail_url text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (source, external_id, category)
);

create index government_opportunities_status_idx on government_opportunities(status);
create index government_opportunities_category_idx on government_opportunities(category);
create index government_opportunities_closing_idx on government_opportunities(closing_date);

alter table government_opportunities enable row level security;

-- Read-only for regular users — this table is machine-generated by the
-- scraper (service-role key, bypasses RLS), never edited by hand.
create policy "government_opportunities_select_owner_staff" on government_opportunities
  for select to authenticated
  using (is_owner_or_staff());

create table government_pursuits (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references government_opportunities(id) on delete cascade,
  status text not null default 'watching' check (status in ('watching', 'pursuing', 'submitted', 'declined', 'lost', 'won')),
  notes text,
  updated_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (opportunity_id)
);

create trigger government_pursuits_set_updated_at
  before update on government_pursuits
  for each row execute function set_updated_at();

alter table government_pursuits enable row level security;

create policy "government_pursuits_owner_staff" on government_pursuits
  for all to authenticated
  using (is_owner_or_staff())
  with check (is_owner_or_staff());
